### ISSUE TITLE
Didn't find the 'price' element, trying again later

### ISSUE THREAD

**Issue by mfraser** [eyalzek/price-alert#12]
Tried to use the script this evening, but keep getting:

Didn't find the 'price' element, trying again later

Even though the xpath_selector seems the same. This is with UK site.

**Comment by eyalzek** [comment]
Please share a configuration that can be used to reproduce this

**Comment by codebankco** [comment]
Having the same issue. 
I have attached my config file with my credentials hidden. 
Everything was working fine yesterday.  

[Config_File.zip](https://github.com/eyalzek/price-alert/files/4256272/Config_File.zip)

**Comment by eyalzek** [comment]
@codebankco I dumped the product page I get with the script and this is what I see:
![image](https://user-images.githubusercontent.com/6243438/75364350-e27a0e80-58bb-11ea-82ab-a18bb7742537.png)

i.e there is no price on the product page. Are you outside of the USA region by any chance? When I connected via VPN to a US location it worked as expected.

**Comment by codebankco** [comment]
@eyalzek 
Thanks for the quick reply.  I am inside the US region.  Very strange.  When I follow the URL it is shipped/sold by Amazon.  This is what I am seeing from my view.  
![price-bug](https://user-images.githubusercontent.com/57819270/75364907-6f0bd900-588a-11ea-9741-a48a933a94c8.JPG)

I'm not too sure why this is happening.

**Comment by codebankco** [comment]
Quick update.  It isn't working for any product.  I will do a fresh install of the repo and try again!

**Comment by codebankco** [comment]
Npoe... Very strange.
