### ISSUE TITLE
Issues adapting for warehouse price check

### ISSUE THREAD

**Issue by markaswift** [eyalzek/price-alert#2]
I've attempted to modify the script so I can check warehouse prices... Seems my skills are not up to the job :(

I'd like to pull the prices from a page like this:

https://www.amazon.co.uk/gp/offer-listing/B014GXQ9YW/ref=dp_olp_used?ie=UTF8&condition=used

I know it's outside the scope, but was wondering if someone could help me achieve this?

**Comment by eyalzek** [comment]
I made an attempt to do so, take a look at this branch:
https://github.com/eyalzek/price-alert/tree/uk-offer-listing

Looks like requests to this URL are throttled though, so sometimes the response is 503 instead of 200. Should work though on the first run I think.

**Comment by eyalzek** [comment]
Closing this as this is not part of the scope for the project at the moment...
